import type { Venue } from "../types";

/** Generated by scripts/ingest.py. Edit data/venue-seed.json or data/venue-overrides.json instead. */
export const venues: Venue[] = [
  {
    "id": "pilar-corrias",
    "name": "Pilar Corrias",
    "type": "commercial",
    "address": "51 Conduit Street",
    "postcode": "W1S 2YT",
    "coordinates": {
      "lat": 51.512028,
      "lng": -0.141676
    },
    "area": "Central",
    "website": "https://www.pilarcorrias.com/",
    "whatsOnUrl": "https://www.pilarcorrias.com/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 2
  },
  {
    "id": "chisenhale-gallery",
    "name": "Chisenhale Gallery",
    "type": "independent",
    "address": "64 Chisenhale Road",
    "postcode": "E3 5QZ",
    "coordinates": {
      "lat": 51.533629,
      "lng": -0.038451
    },
    "area": "City & East",
    "website": "https://chisenhale.org.uk/",
    "whatsOnUrl": "https://chisenhale.org.uk/whats-on/",
    "openingHours": {
      "wednesday": {
        "open": "12:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "12:00",
        "close": "18:00"
      },
      "friday": {
        "open": "12:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "12:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "12:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 7
  },
  {
    "id": "october-gallery",
    "name": "October Gallery",
    "type": "independent",
    "address": "24 Old Gloucester Street London",
    "postcode": "WC1N 3AL",
    "coordinates": {
      "lat": 51.520694,
      "lng": -0.121705
    },
    "area": "Central",
    "website": "https://www.octobergallery.co.uk/",
    "whatsOnUrl": "https://www.octobergallery.co.uk/exhibitions/",
    "openingHours": {
      "tuesday": {
        "open": "12:30",
        "close": "17:30"
      },
      "wednesday": {
        "open": "12:30",
        "close": "17:30"
      },
      "thursday": {
        "open": "12:30",
        "close": "17:30"
      },
      "friday": {
        "open": "12:30",
        "close": "17:30"
      },
      "saturday": {
        "open": "12:30",
        "close": "17:30"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 10
  },
  {
    "id": "hannah-barry-gallery",
    "name": "Hannah Barry Gallery",
    "type": "commercial",
    "address": "4 Holly Grove, Peckham",
    "postcode": "SE15 5DF",
    "coordinates": {
      "lat": 51.469744,
      "lng": -0.071517
    },
    "area": "South East",
    "website": "https://hannahbarry.com/",
    "whatsOnUrl": "https://hannahbarry.com/exhibitions",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 14
  },
  {
    "id": "kristin-hjellegjerde-gallery",
    "name": "Kristin Hjellegjerde Gallery",
    "type": "commercial",
    "address": "36 Tanner Street",
    "postcode": "SE1 3LD",
    "coordinates": {
      "lat": 51.499714,
      "lng": -0.079502
    },
    "area": "South Bank & Bankside",
    "website": "https://kristinhjellegjerde.com/",
    "whatsOnUrl": "https://kristinhjellegjerde.com/exhibitions",
    "openingHours": {
      "monday": {
        "open": "11:00",
        "close": "18:00"
      },
      "tuesday": {
        "open": "11:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "11:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "11:00",
        "close": "18:00"
      },
      "friday": {
        "open": "11:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "11:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 16
  },
  {
    "id": "matts-gallery",
    "name": "Matt's Gallery",
    "type": "independent",
    "address": "6 Charles Clowes Walk, Nine Elms",
    "postcode": "SW11 7AN",
    "coordinates": {
      "lat": 51.481047,
      "lng": -0.132567
    },
    "area": "South West & Lambeth",
    "website": "https://www.mattsgallery.org/",
    "whatsOnUrl": "https://www.mattsgallery.org/exhibitions",
    "openingHours": {
      "wednesday": {
        "open": "12:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "12:00",
        "close": "18:00"
      },
      "friday": {
        "open": "12:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "12:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "12:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 17
  },
  {
    "id": "hales-gallery",
    "name": "Hales Gallery",
    "type": "commercial",
    "address": "7 Bethnal Green Road",
    "postcode": "E1 6LA",
    "coordinates": {
      "lat": 51.524203,
      "lng": -0.073614
    },
    "area": "City & East",
    "website": "https://halesgallery.com/",
    "whatsOnUrl": "https://halesgallery.com/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 20
  },
  {
    "id": "victoria-miro",
    "name": "Victoria Miro",
    "type": "commercial",
    "address": "16 Wharf Road",
    "postcode": "N1 7RW",
    "coordinates": {
      "lat": 51.53038,
      "lng": -0.095008
    },
    "area": "North",
    "website": "https://www.victoria-miro.com/",
    "whatsOnUrl": "https://www.victoria-miro.com/exhibitions/",
    "openingHours": {
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 22
  },
  {
    "id": "tate-britain",
    "name": "Tate Britain",
    "type": "national",
    "address": "Millbank",
    "postcode": "SW1P 4RG",
    "coordinates": {
      "lat": 51.490871,
      "lng": -0.127181
    },
    "area": "South West & Lambeth",
    "website": "https://www.tate.org.uk/visit/tate-britain",
    "whatsOnUrl": "https://www.tate.org.uk/whats-on/tate-britain",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "18:00"
      },
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 23
  },
  {
    "id": "whitechapel-gallery",
    "name": "Whitechapel Gallery",
    "type": "public",
    "address": "77–82 Whitechapel High Street",
    "postcode": "E1 7QX",
    "coordinates": {
      "lat": 51.516012,
      "lng": -0.070399
    },
    "area": "City & East",
    "website": "https://www.whitechapelgallery.org/",
    "whatsOnUrl": "https://www.whitechapelgallery.org/exhibitions/",
    "openingHours": {
      "tuesday": {
        "open": "11:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "11:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "11:00",
        "close": "21:00"
      },
      "friday": {
        "open": "11:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "11:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "11:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 26
  },
  {
    "id": "sadie-coles-hq",
    "name": "Sadie Coles HQ",
    "type": "commercial",
    "address": "17 Savile Row",
    "postcode": "W1S 3PN",
    "coordinates": {
      "lat": 51.511351,
      "lng": -0.140349
    },
    "area": "Central",
    "website": "https://www.sadiecoles.com/",
    "whatsOnUrl": "https://www.sadiecoles.com/exhibitions/",
    "openingHours": {
      "tuesday": {
        "open": "11:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "11:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "11:00",
        "close": "18:00"
      },
      "friday": {
        "open": "11:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "11:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 39
  },
  {
    "id": "the-redfern-gallery",
    "name": "The Redfern Gallery",
    "type": "commercial",
    "address": "11–12 Pall Mall",
    "postcode": "SW1Y 5LU",
    "coordinates": {
      "lat": 51.507043,
      "lng": -0.133521
    },
    "area": "Central",
    "website": "https://www.redfern-gallery.com/",
    "whatsOnUrl": "https://www.redfern-gallery.com/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 40
  },
  {
    "id": "david-zwirner-london",
    "name": "David Zwirner London",
    "type": "commercial",
    "address": "24 Grafton Street",
    "postcode": "W1S 4EZ",
    "coordinates": {
      "lat": 51.509477,
      "lng": -0.143005
    },
    "area": "Central",
    "website": "https://www.davidzwirner.com/locations/london",
    "whatsOnUrl": "https://www.davidzwirner.com/exhibitions",
    "openingHours": {
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 42
  },
  {
    "id": "the-courtauld-gallery",
    "name": "The Courtauld Gallery",
    "type": "national",
    "address": "Somerset House, Strand",
    "postcode": "WC2R 0RN",
    "coordinates": {
      "lat": 51.510734,
      "lng": -0.116912
    },
    "area": "Central",
    "website": "https://courtauld.ac.uk/gallery/",
    "whatsOnUrl": "https://courtauld.ac.uk/whats-on/",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "18:00"
      },
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 45
  },
  {
    "id": "maddox-gallery",
    "name": "Maddox Gallery",
    "type": "commercial",
    "address": "9 Maddox Street London",
    "postcode": "W1S 2QE",
    "coordinates": {
      "lat": 51.513312,
      "lng": -0.141538
    },
    "area": "Central",
    "website": "https://maddoxgallery.com/",
    "whatsOnUrl": "https://maddoxgallery.com/exhibitions/",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "18:00"
      },
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 46
  },
  {
    "id": "royal-academy",
    "name": "Royal Academy of Arts",
    "type": "public",
    "address": "Burlington House, Piccadilly",
    "postcode": "W1J 0BD",
    "coordinates": {
      "lat": 51.509099,
      "lng": -0.139576
    },
    "area": "Central",
    "website": "https://www.royalacademy.org.uk/",
    "whatsOnUrl": "https://www.royalacademy.org.uk/exhibitions-and-events",
    "openingHours": {
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "21:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "21:00"
      },
      "sunday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 49
  },
  {
    "id": "national-gallery",
    "name": "The National Gallery",
    "type": "national",
    "address": "Trafalgar Square",
    "postcode": "WC2N 5DN",
    "coordinates": {
      "lat": 51.509098,
      "lng": -0.127658
    },
    "area": "Central",
    "website": "https://www.nationalgallery.org.uk/",
    "whatsOnUrl": "https://www.nationalgallery.org.uk/exhibitions",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "18:00"
      },
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "21:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 50
  },
  {
    "id": "lbf-contemporary",
    "name": "LBF Contemporary",
    "type": "commercial",
    "address": "13 Tottenham Mews",
    "postcode": "W1T 4AQ",
    "coordinates": {
      "lat": 51.520512,
      "lng": -0.137367
    },
    "area": "Central",
    "website": "https://www.lbfcontemporary.com/",
    "whatsOnUrl": "https://www.lbfcontemporary.com/exhibitions",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 52
  },
  {
    "id": "blueshop-cottage",
    "name": "Blue Shop Cottage",
    "type": "commercial",
    "address": "72 Brixton Road, Oval",
    "postcode": "SW9 6BH",
    "coordinates": {
      "lat": 51.478127,
      "lng": -0.112466
    },
    "area": "South West & Lambeth",
    "website": "https://www.blueshopcottage.com/",
    "whatsOnUrl": "https://www.blueshopcottage.com/exhibitions",
    "openingHours": {
      "thursday": {
        "open": "12:00",
        "close": "17:00"
      },
      "friday": {
        "open": "12:00",
        "close": "17:00"
      },
      "saturday": {
        "open": "12:00",
        "close": "17:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": 53
  },
  {
    "id": "annely-juda-fine-art",
    "name": "Annely Juda Fine Art",
    "type": "commercial",
    "address": "16 Hanover Square",
    "postcode": "W1S 1HT",
    "coordinates": {
      "lat": 51.513445,
      "lng": -0.141402
    },
    "area": "Central",
    "website": "https://www.annelyjudafineart.co.uk/",
    "whatsOnUrl": "https://www.annelyjudafineart.co.uk/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "auto-italia",
    "name": "Auto Italia",
    "type": "independent",
    "address": "44 Bonner Road",
    "postcode": "E2 9JS",
    "coordinates": {
      "lat": 51.532226,
      "lng": -0.051979
    },
    "area": "City & East",
    "website": "https://autoitaliasoutheast.org/",
    "whatsOnUrl": "https://autoitaliasoutheast.org/",
    "openingHours": {
      "thursday": {
        "open": "12:00",
        "close": "17:00"
      },
      "friday": {
        "open": "12:00",
        "close": "17:00"
      },
      "saturday": {
        "open": "12:00",
        "close": "17:00"
      },
      "sunday": {
        "open": "12:00",
        "close": "17:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "camden-art-centre",
    "name": "Camden Art Centre",
    "type": "independent",
    "address": "Arkwright Road",
    "postcode": "NW3 6DG",
    "coordinates": {
      "lat": 51.551252,
      "lng": -0.183466
    },
    "area": "North",
    "website": "https://camdenartcentre.org/",
    "whatsOnUrl": "https://camdenartcentre.org/whats-on/",
    "openingHours": {
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "21:00"
      },
      "friday": {
        "open": "10:00",
        "close": "18:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "18:00"
      },
      "sunday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "design-museum",
    "name": "Design Museum",
    "type": "independent",
    "address": "224–238 Kensington High Street",
    "postcode": "W8 6AG",
    "coordinates": {
      "lat": 51.499874,
      "lng": -0.200163
    },
    "area": "South Kensington & West",
    "website": "https://designmuseum.org/",
    "whatsOnUrl": "https://designmuseum.org/exhibitions",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "dulwich-picture-gallery",
    "name": "Dulwich Picture Gallery",
    "type": "independent",
    "address": "14 Gallery Road",
    "postcode": "SE21 7AD",
    "coordinates": {
      "lat": 51.445613,
      "lng": -0.08668
    },
    "area": "South East",
    "website": "https://www.dulwichpicturegallery.org.uk/",
    "whatsOnUrl": "https://www.dulwichpicturegallery.org.uk/whats-on/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "garden-museum",
    "name": "Garden Museum",
    "type": "independent",
    "address": "Lambeth Palace Road London",
    "postcode": "SE1 7LB",
    "coordinates": {
      "lat": 51.495049,
      "lng": -0.120196
    },
    "area": "South Bank & Bankside",
    "website": "https://gardenmuseum.org.uk/",
    "whatsOnUrl": "https://gardenmuseum.org.uk/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "gasworks",
    "name": "Gasworks",
    "type": "independent",
    "address": "155 Vauxhall Street",
    "postcode": "SE11 5RH",
    "coordinates": {
      "lat": 51.486632,
      "lng": -0.116278
    },
    "area": "South West & Lambeth",
    "website": "https://www.gasworks.org.uk/",
    "whatsOnUrl": "https://www.gasworks.org.uk/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "national-portrait-gallery",
    "name": "National Portrait Gallery",
    "type": "national",
    "address": "St Martin's Place",
    "postcode": "WC2H 0HE",
    "coordinates": {
      "lat": 51.509399,
      "lng": -0.128453
    },
    "area": "Central",
    "website": "https://www.npg.org.uk/",
    "whatsOnUrl": "https://www.npg.org.uk/whatson/events-calendar/?what=exhibition",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "sir-john-soanes-museum",
    "name": "Sir John Soane's Museum",
    "type": "national",
    "address": "13 Lincoln's Inn Fields",
    "postcode": "WC2A 3BP",
    "coordinates": {
      "lat": 51.516956,
      "lng": -0.117953
    },
    "area": "Central",
    "website": "https://www.soane.org/",
    "whatsOnUrl": "https://www.soane.org/whats-on",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "south-london-gallery",
    "name": "South London Gallery",
    "type": "independent",
    "address": "65–67 and 82 Peckham Road",
    "postcode": "SE5 8UH",
    "coordinates": {
      "lat": 51.474002,
      "lng": -0.081087
    },
    "area": "South East",
    "website": "https://www.southlondongallery.org/",
    "whatsOnUrl": "https://www.southlondongallery.org/exhibitions/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "tate-modern",
    "name": "Tate Modern",
    "type": "national",
    "address": "Bankside",
    "postcode": "SE1 9TG",
    "coordinates": {
      "lat": 51.507618,
      "lng": -0.099374
    },
    "area": "South Bank & Bankside",
    "website": "https://www.tate.org.uk/visit/tate-modern",
    "whatsOnUrl": "https://www.tate.org.uk/whats-on/tate-modern",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "18:00"
      },
      "tuesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "wednesday": {
        "open": "10:00",
        "close": "18:00"
      },
      "thursday": {
        "open": "10:00",
        "close": "18:00"
      },
      "friday": {
        "open": "10:00",
        "close": "21:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "21:00"
      },
      "sunday": {
        "open": "10:00",
        "close": "18:00"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "vam",
    "name": "V&A South Kensington",
    "type": "national",
    "address": "Cromwell Road",
    "postcode": "SW7 2RL",
    "coordinates": {
      "lat": 51.496941,
      "lng": -0.172199
    },
    "area": "South Kensington & West",
    "website": "https://www.vam.ac.uk/south-kensington",
    "whatsOnUrl": "https://www.vam.ac.uk/whatson",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "17:45"
      },
      "tuesday": {
        "open": "10:00",
        "close": "17:45"
      },
      "wednesday": {
        "open": "10:00",
        "close": "17:45"
      },
      "thursday": {
        "open": "10:00",
        "close": "17:45"
      },
      "friday": {
        "open": "10:00",
        "close": "22:00"
      },
      "saturday": {
        "open": "10:00",
        "close": "17:45"
      },
      "sunday": {
        "open": "10:00",
        "close": "17:45"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "wallace-collection",
    "name": "Wallace Collection",
    "type": "national",
    "address": "Hertford House, Manchester Square",
    "postcode": "W1U 3BN",
    "coordinates": {
      "lat": 51.517314,
      "lng": -0.152949
    },
    "area": "Central",
    "website": "https://www.wallacecollection.org/",
    "whatsOnUrl": "https://www.wallacecollection.org/whats-on/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "wellcome-collection",
    "name": "Wellcome Collection",
    "type": "independent",
    "address": "183 Euston Road",
    "postcode": "NW1 2BE",
    "coordinates": {
      "lat": 51.525898,
      "lng": -0.133918
    },
    "area": "Central",
    "website": "https://wellcomecollection.org/",
    "whatsOnUrl": "https://wellcomecollection.org/exhibitions",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "young-vam",
    "name": "Young V&A",
    "type": "national",
    "address": "Cambridge Heath Road, Bethnal Green",
    "postcode": "E2 9PA",
    "coordinates": {
      "lat": 51.527774,
      "lng": -0.055182
    },
    "area": "City & East",
    "website": "https://www.vam.ac.uk/young/",
    "whatsOnUrl": "https://www.vam.ac.uk/whatson",
    "openingHours": {
      "monday": {
        "open": "10:00",
        "close": "17:45"
      },
      "tuesday": {
        "open": "10:00",
        "close": "17:45"
      },
      "wednesday": {
        "open": "10:00",
        "close": "17:45"
      },
      "thursday": {
        "open": "10:00",
        "close": "17:45"
      },
      "friday": {
        "open": "10:00",
        "close": "17:45"
      },
      "saturday": {
        "open": "10:00",
        "close": "17:45"
      },
      "sunday": {
        "open": "10:00",
        "close": "17:45"
      }
    },
    "hoursLastChecked": "2026-10-06",
    "scrapeMethod": "website",
    "lastSuccessfulScrape": "2026-10-06",
    "priorityRank": null
  },
  {
    "id": "refuses-at-queensrollahouse",
    "name": "Refusés at Queensrollahouse",
    "type": "independent",
    "address": "18 Trading Estate Road",
    "postcode": "NW10 7LU",
    "coordinates": {
      "lat": 51.526479,
      "lng": -0.268658
    },
    "area": "South Kensington & West",
    "website": "https://refuses.info/",
    "whatsOnUrl": "https://refuses.info/Archive",
    "instagramUrl": "https://www.instagram.com/r.efuses/",
    "openingHours": null,
    "hoursLastChecked": null,
    "scrapeMethod": "link-only",
    "lastSuccessfulScrape": null,
    "priorityRank": null
  }
];
